apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-portal
  template:
    metadata:
      labels:
        app: learning-portal
    spec:
      containers:
        - name: learning-portal
          image: 07rochak/ef16ea49f002:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: learning-portal
spec:
  type: NodePort
  selector:
    app: learning-portal
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32000